#!/bin/bash
### Ruby install script
source ~/.rvm/scripts/rvm
rvm requirements
rvm install 2.4.1
rvm use 2.4.1 --default
gem install bundler -V --no-ri --no-rdoc
### MongoDB install script
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
sudo bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo systemctl start mongod
sudo systemctl enable mongod
sudo systemctl status mongod
### Deploy
git clone https://github.com/Artemmkin/reddit.git
cd reddit && bundle install
### export SERVER_IP=146.148.124.3
### export REPO_NAME=Leonteviu/reddit
### export DEPLOY_USER=appuser
puma -d
